### PR TITLE
Gh135   fix pin logic

### LINKED ISSUE #135: Fix pin logic

### PR DESCRIPTION
**Pull request by cormacmccarthy**
fixes #135 

Makes it easier for pinned player to break free the longer they are pinned.

### CODE REVIEW

File: cards/immobilize.js [hunk 1]
```diff
@@ -116,6 +121,7 @@ class ImmobilizeCard extends HitCard {
 				});
 
 				if (attackSuccess.success) {
+					target.pinnedTurns = 0;
```
Comment (tweettypography) [inline cards/immobilize.js]: I know, this gets reset, but I'm not crazy about editing the actual player here as you'd be editing their master instance. I don't see that you made `pinnedTurns` part of their encounter properties, so they wouldn't get cleaned up. An alternative would be tracking it on the card (as that is a copy) or adding it to encounter properties.

Comment (cormacmccarthy) [reply cards/immobilize.js]: I'll figure out how to add to encounter properties... Pretty sure there's an example of it somewhere.

Comment (cormacmccarthy) [reply cards/immobilize.js]: @tweettypography done.
